### ISSUE TITLE
npm install -g t2-cli fails without "sudo" on OSX due to no access to /usr/local/bin

### ISSUE THREAD

**Issue by flaki** [tessel/t2-start#57] opened 2015-10-17 21:39 UTC
Even with proper `~/.npm` permissions, one needs `sudo` anyway, because otherwise `install -g` fails due to not being able to access `/usr/local/bin/t2`:

```
npm ERR! Error: EACCES, unlink '/usr/local/bin/t2'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/usr/local/bin/t2'] errno: -13, code: 'EACCES', path: '/usr/local/bin/t2' }
```

**Comment by tcr** [comment] 2015-10-18 15:12
@flaki It looks like npm is trying to _uninstall_ a previously linked version of T2 in /usr/local/bin/t2. Can you see if that file exists already?

`ls /usr/local/bin/t2`

If you delete that file manually, then try running `npm install -g t2-cli`, does that succeed? At least, it should fail with a different error.

**Comment by LinusU** [comment] 2015-10-19 09:08
How did you install Node.js on your system? OS X doesn't use `/usr/local` at all by default, which is why `brew` has taken that for it self. It `chown`s it into your local user thought, so you should actually have permissions to edit `/usr/local/bin/t2`.

This can actually easily break if you at any point use sudo thought, since that will create the new files as the root user.

Could you try running `brew doctor`?

**Comment by jverne** [comment] 2016-04-11 13:45
I'm going to jump in here and present a related and contrary opinion.

While /usr/local is not a "system" location, it is a _system-wide_ location, and is automatically on the PATH for new accounts. This has **many** implications for security. Now, I don't want to participate in what is a bit of a holy war around Homebrew installation choices, but many people do not agree that this location should be owned by non-privileged users on a multi-user system.

Certainly, most other things would expect to be installed as a privileged user to this location. I can't think of a single app I've every installed that wouldn't. Only Homebrew has made this decision as far as I know, which is a bit like saying "we own this location, contrary to good practices".

At the very least, the issue is that no one should depend on /usr/local being accessible by a non-privileged user, because Homebrew is an outlier here. This means that both t2 and npm might not actually have the access they need, and this only partially depends on if Homebrew is used or not.

What this comes down to is that dependent apps like t2 are going to behave differently if Homebrew is used to install Node.js and npm or not, and what else has been done to this system-wide location since Node.js/npm/t2 was installed.

**Comment by Frijol** [comment] 2016-04-15 18:23
closing this issue in favor of https://github.com/tessel/t2-start/issues/106

**Closed as completed by Frijol** 2016-04-15 18:23 UTC
