### ISSUE TITLE
Confused about instructions for setup

### ISSUE THREAD

**Issue by aperala** [tessel/t2-start#52] opened 2015-10-17 19:37 UTC
New user here. I was following the instructions for "Find Your Tessel" and was a little confused when it returned multiple Tessels:

<img width="873" alt="screen shot 2015-10-17 at 3 33 50 pm" src="https://cloud.githubusercontent.com/assets/12714591/10560840/d3a27916-74e4-11e5-9415-8f5d191939dc.png">

I didn't realize that other Tessels on the LAN would be returned. Maybe clarify that the USB connection is the one new users are looking for.

**Comment by Student007** [comment] 2015-10-18 10:55
https://github.com/tessel/t2-cli/pull/381 fixes this.

**Comment by Frijol** [comment] 2015-10-18 14:35
@Student007 please don't close issues until a fix is merged.

**Comment by Student007** [comment] 2015-10-18 15:03
@Frijol ... OK I will simple assign it to **me** :laughing: ... to stop others to do double work.

**Comment by Frijol** [comment] 2015-10-18 15:10
I think a simpler solution to this problem would be a quick change to the start page copy

from this:
![screen shot 2015-10-18 at 11 09 27 am](https://cloud.githubusercontent.com/assets/454690/10564619/bfba490c-7588-11e5-8ce9-8a54cdd7630a.png)

to this:
![screen shot 2015-10-18 at 11 09 21 am](https://cloud.githubusercontent.com/assets/454690/10564620/c4617106-7588-11e5-88ca-ca95b40954a7.png)

**Comment by Student007** [comment] 2015-10-18 15:18
@Frijol I think it is both necessary - **Usability** is to point users onto things when they need them. But also teach people reading the docs. There are a lot of people out there mean things promise usability do not require them to read the docs. They expect: Usability is when I have no questions :wink: 
Of cause at this point it is to discuss to change the conditional `note` variable setting to have different messages to new users.

**Comment by Frijol** [comment] 2015-10-18 15:30
I agree with that sentiment. However, I don't think a usability fix is the correct solution in this case, because:
1. We have no way of knowing which of the Tessels on the network are relevant to the user
2. You only have to learn one time that `t2 list` finds any Tessels on the network; after that, this is expected behavior

**Comment by rwaldron** [comment] 2015-10-18 15:48
@Frijol 

> I think a simpler solution to this problem would be a quick change to the start page copy

Agreed.

**Comment by Student007** [comment] 2015-10-18 15:52
> New user here. I was following the instructions for "Find Your Tessel" and was a **little confused when it returned multiple Tessels** [...]

This will happen at events with free WLAN all the time ...

> I didn't realize that other Tessels on the LAN would be returned. 

@Frijol this is covered by your doc fix suggestion (I agree).

> **Maybe clarify that the USB connection is the one new users are looking for.**

**Mr. Speaker**: _the blue one is yours_ 

(the red Tessels found are either others or your second one)

I though about to make the provisioned and authorized Tessels **green** but while testing several terminals I though it would better stay native.

**Comment by Frijol** [comment] 2016-05-17 14:44
I haven't seen this difficulty recently, closing. Can re-open if it resurfaces

**Closed as completed by Frijol** 2016-05-17 14:44 UTC
Labels: contribution-starter
